"""initial schema

Revision ID: 9a753ce4f1c4
Revises:
Create Date: 2026-09-06 21:45:24.573858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9a753ce4f1c4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column(
            "name_normalized",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=False,
        ),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "date",
            "name_normalized",
            name="uq_activities_user_date_name_norm",
        ),
    )
    op.create_index(op.f("ix_activities_date"), "activities", ["date"], unique=False)
    op.create_index(
        op.f("ix_activities_name_normalized"),
        "activities",
        ["name_normalized"],
        unique=False,
    )
    op.create_index(
        "ix_activities_user_date", "activities", ["user_id", "date"], unique=False
    )
    op.create_index(
        "ix_activities_user_date_name",
        "activities",
        ["user_id", "date", "name_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_user_id"), "activities", ["user_id"], unique=False
    )
    op.create_table(
        "life_areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_life_areas_user_id"), "life_areas", ["user_id"], unique=False
    )
    op.create_table(
        "activity_areas",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["area_id"], ["life_areas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "area_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_areas")
    op.drop_index(op.f("ix_life_areas_user_id"), table_name="life_areas")
    op.drop_table("life_areas")
    op.drop_index(op.f("ix_activities_user_id"), table_name="activities")
    op.drop_index("ix_activities_user_date_name", table_name="activities")
    op.drop_index("ix_activities_user_date", table_name="activities")
    op.drop_index(op.f("ix_activities_name_normalized"), table_name="activities")
    op.drop_index(op.f("ix_activities_date"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
